export const initialValuesStates = {
  loading: false,
  employees: [],
  persons: [],
  documentTypes: [],
  genders: [],
  cities: [],
  company: [],
  maritalStatus: [],
  salaryType: [],
  profession: [],
  educationLevel: [],
  englishLevel: [],
  campus: [],
  sexualPreference: [],
  disabilities: [],
  hiringType: [],
  contractType: [],
  organizationalLevel: [],
  workingDay: [],
  rols: [],
  areas: [],
};
